### ISSUE TITLE
[Feature Request][Bounty Offered] Popups on Ankidroid after selecting a word

### ISSUE THREAD

**Issue by Kewell35** [lucwastiaux/AnkiReview#15]
I already have the ankidesktop add-on for this but would like it work on ankidroid. When I select a word while reviewing cards, a popup automatically appears that brings up all the cards in the deck that contains that word.

I would like to have the same thing work on ankidroid. When I select a word on ankidroid, a popup box appears that shows you all the previous cards in the current deck with the same word.

I already have the original add-on so it's just to make it work for ankidroid.

This is the add-on I was referring to.
https://ankiweb.net/shared/info/153625306

I'm willing to hire someone to code this for me. Is anyone interested?

**Comment by luc-vocab** [comment]
this is not easy to accomplish at all whether within AnkiDroid or AnkiReview. Bringing up cards before they are due for a review is not something that is going to be easily done given how the front-end and the scheduler communicate. This is going to be some serious development work, probably will entail writing a whole new app. And the cost will probably be way more than what you expect.
